[package]
name = "dassai"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.86"
bpaf = { version = "0.9.12", features = ["derive"] }
walkdir = "2.5.0"
