newline_style = "Unix"
match_block_trailing_comma = true
use_field_init_shorthand = true
use_try_shorthand = true

# nightly-only features
unstable_features = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
condense_wildcard_suffixes = true
overflow_delimited_expr = true
reorder_impl_items = true
format_strings = true
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
